development:
  adapter: solid_cable
  connects_to:
    database:
      writing: primary
  polling_interval: 0.1.seconds
  message_retention: 1.hour

test:
  adapter: test

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: primary
  polling_interval: 0.5.seconds
  message_retention: 10.minutes
